# Azure YAML Pipeline Template Documentation
#
# Overview:
#
# This template runs a terraform apply command for a specified workload and
# environment against the subscription configured in the service connection.
#
# Assumptions:
#
# This template assumes the necessary Terraform files and plan are present in the working directory.
# It also assumes that the appropriate Azure service connection is available.

parameters:
  - name: working_directory
    type: string
  - name: azurerm_service_connection
    type: string
  - name: securevars_file
    type: string
  - name: parallelism
    type: number
    default: 10
  - name: command_option_args
    type: string
    default: ''
  - name: destroy_mode
    type: string
    default: '0'
  - name: plan_file_name
    type: string
    default: 'terraform.tfplan'


steps:
  - task: TerraformCLI@1
    displayName: 'Run a terraform apply'
    inputs:
      command: 'apply'
      ${{ if eq(parameters.destroy_mode, '1') }}:
        commandOptions: '-destroy -input=false -parallelism=${{ parameters.parallelism }} -auto-approve ${{ parameters.plan_file_name }}'
      ${{ else }}:
        commandOptions: '-input=false -parallelism=${{ parameters.parallelism }} ${{ parameters.command_option_args }} -auto-approve ${{ parameters.plan_file_name }}'
      workingDirectory: ${{ parameters.working_directory }}
      secureVarsFile: ${{ parameters.securevars_file }}
      environmentServiceName: ${{ parameters.azurerm_service_connection }}
