# Azure YAML Pipeline Template Documentation
#
# Overview:
#
# This template runs a terraform apply command for a specified workload and
# environment against the subscription configured in the service connection.
#
# Assumptions:
#
# This template assumes the necessary Terraform files and plan are present in the working directory.
# It also assumes that the appropriate Azure service connection is available.

parameters:
  - name: workload
    type: string
  - name: environment
    type: string
  - name: working_directory
    type: string
  - name: azurerm_service_connection
    type: string
  - name: tfvars_file
    type: string
  - name: securevars_file
    type: string
    default: ''
  - name: parallelism
    type: number
    default: 10
  - name: command_option_args
    type: string
    default: ''
  - name: destroy_mode
    type: boolean
    default: false
  - name: smoke_test_mode
    type: boolean
    default: false
  - name: plan_file_name
    type: string
    default: 'terraform.tfplan'


steps:
  - task: TerraformCLI@0
    displayName: 'Run a terraform apply'
    inputs:
      command: 'apply'
      workingDirectory: ${{ parameters.working_directory }}
      environmentServiceName: ${{ parameters.azurerm_service_connection }}
      ${{ if eq(parameters.destroy_mode, true) }}:
        commandOptions: '-destroy -input=false -parallelism=${{ parameters.parallelism }} -auto-approve ${{ parameters.plan_file_name }}'
      ${{ else }}:
        commandOptions: '-input=false -parallelism=${{ parameters.parallelism }} ${{ parameters.command_option_args }} -auto-approve ${{ parameters.plan_file_name }}'

  - task: TerraformCLI@0
    condition: eq('${{ parameters.smoke_test_mode }}', true)
    displayName: 'Verify formatting'
    inputs:
      azurerm_service_connection: ${{ parameters.azurerm_service_connection }}
      working_directory: ${{ parameters.working_directory }} 
      workload: '${{ parameters.workload }}'
      environment: '${{ environment.environment }}'
      securevars_file: ${{ parameters.securevars_file }}
      tfvars_file: '${{ environment.tfvars_file }}'
      command_option_args: '${{ environment.command_option_args }}'