# Azure YAML Pipeline Template Documentation
#
# Overview:
#
# This template runs security tools against the Terraform files in the specified working directory.
#
# Assumptions:
#
# This template assumes that the necessary Terraform files are present in the working directory.
#

parameters:
  - name: working_directory
    type: string
  - name: command_option_args
    type: string
    default: ''
  - name: run_msdefender
    type: boolean
    default: true
  - name: run_tfsec
    type: boolean
    default: true

steps:
  - task: MicrosoftSecurityDevOps@1
    condition: and(succeeded(), ne('${{ parameters.run_msdefender }}', false))
    displayName: 'Run Defender for AzureDevOps'
    inputs:
      tools: '__security_tools__' 
      workingDirectory: ${{ parameters.working_directory }}
  - task: tfsec@1
    condition: and(succeeded(), ne('${{ parameters.run_tfsec }}', false))
    displayName: 'Run tfsec'
    inputs:
      dir: ${{ parameters.working_directory }}
      args: ${{ parameters.command_option_args }}