# .github/workflows/install.yml
name: Install Terraform

on:
  workflow_call:

jobs:
  install:
    name: Install Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version || 'latest' }}
