# .github/workflows/stages.deploy.yml
name: Terraform CI/CD Orchestration

on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Terraform version'
        required: false
        default: 'latest'
        type: string
      working_directory:
        description: 'Working directory'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      plan_file_name:
        description: 'Terraform plan file name'
        required: false
        default: 'terraform.tfplan'
        type: string
      var_file:
        description: 'Terraform variables file'
        required: false
        default: ''
        type: string

jobs:
  validate:
    name: Validate Stage
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: echo "Hello World!"

  # install:
  #   name: Install Terraform
  #   runs-on: ubuntu-latest
  #   needs: validate
  #   uses: ./.github/workflows/tf_install_task.yml
  #   with:
  #     tf_version: ${{ inputs.tf_version }}

  # init:
  #   name: Initialize Terraform
  #   runs-on: ubuntu-latest
  #   needs: install
  #   uses: ./.github/workflows/tf_init_task.yml
  #   with:
  #     working_directory: ${{ inputs.working_directory }}
  #     backend_configs: ${{ inputs.backend_configs }}

  # plan:
  #   name: Plan Terraform
  #   runs-on: ubuntu-latest
  #   needs: init
  #   uses: ./.github/workflows/tf_plan_task.yml
  #   with:
  #     working_directory: ${{ inputs.working_directory }}
  #     plan_file_name: ${{ inputs.plan_file_name }}
  #     var_file: ${{ inputs.var_file }}

  # apply:
  #   name: Apply Terraform
  #   runs-on: ubuntu-latest
  #   needs: plan
  #   uses: ./.github/workflows/tf_apply_task.yml
  #   with:
  #     working_directory: ${{ inputs.working_directory }}
  #     plan_file_name: ${{ inputs.plan_file_name }}
