# .github/workflows/stages.deploy.yml
name: Terraform CI/CD Orchestration

on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Terraform version'
        required: false
        default: 'latest'
        type: string
      working_directory:
        description: 'Working directory'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      plan_file_name:
        description: 'Terraform plan file name'
        required: false
        default: 'terraform.tfplan'
        type: string
      var_file:
        description: 'Terraform variables file'
        required: false
        default: ''
        type: string

jobs:
  validate:
    name: Validate Stage
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: echo "Hello World! ${{ inputs.tf_version }}"
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Initialize Terraform
        run: terraform init -input=false -backend-config="${{ inputs.backend_configs }}"
        working-directory: ${{ inputs.working_directory }}

      - name: Validate Terraform
        run: terraform validate
        working-directory: ${{ inputs.working_directory }}
        
  # plan:
  #   name: Plan Stage
  #   runs-on: ubuntu-latest
  #   needs: validate
  #   steps:
  #     - name: Install Terraform
  #       run: echo "Installing Terraform version ${{ inputs.tf_version }}..."
  #       # Add your actual Terraform installation command here

  #     - name: Initialize Terraform
  #       run: echo "Initializing Terraform in ${{ inputs.working_directory }}..."
  #       # Add your actual Terraform init command here

  #     - name: Plan Terraform
  #       run: echo "Planning Terraform..."
  #       # Add your actual Terraform plan command here

  # apply:
  #   name: Apply Stage
  #   runs-on: ubuntu-latest
  #   needs: plan
  #   steps:
  #     - name: Install Terraform
  #       run: echo "Installing Terraform version ${{ inputs.tf_version }}..."
  #       # Add your actual Terraform installation command here

  #     - name: Initialize Terraform
  #       run: echo "Initializing Terraform in ${{ inputs.working_directory }}..."
  #       # Add your actual Terraform init command here

  #     - name: Apply Terraform
  #       run: echo "Applying Terraform..."
  #       # Add your actual Terraform apply command here