# .github/workflows/stages.deploy.yml
name: Terraform CI/CD Orchestration

on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Terraform version'
        required: false
        default: 'latest'
        type: string
      working_directory:
        description: 'Working directory'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      backend_configs:
        description: 'Backend configurations'
        required: true
        type: object
      plan_file_name:
        description: 'Terraform plan file name'
        required: false
        default: 'terraform.tfplan'
        type: string
      var_file:
        description: 'Terraform variables file'
        required: false
        default: ''
        type: string

jobs:
  validate:
    name: Validate Stage
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: echo "Hello World! ${{ inputs.tf_version }}"
      
      - name: List Directory Files
        run: ls

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Check Terraform Formatting
        run: terraform fmt --check --diff -recursive
        working-directory: ${{ inputs.working_directory }}

      - name: Initialize Terraform
        run: terraform init -input=false -backend-config="${{ inputs.backend_configs }}"
        working-directory: ${{ inputs.working_directory }}

      - name: Validate Terraform
        run: terraform validate
        working-directory: ${{ inputs.working_directory }}
        
  plan:
      name: Plan Stage
      runs-on: ubuntu-latest
      needs: validate
      steps:
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: ${{ inputs.tf_version }}

        - name: Initialize Terraform
          run: terraform init -input=false -backend-config="${{ inputs.backend_configs }}"
          working-directory: ${{ inputs.working_directory }}

        - name: Plan Terraform
          run: terraform plan -out=${{ inputs.plan_file_name }} -var-file=${{ inputs.var_file }}
          working-directory: ${{ inputs.working_directory }}

  apply:
    name: Apply Stage
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Initialize Terraform
        run: terraform init -input=false -backend-config="${{ inputs.backend_configs }}"
        working-directory: ${{ inputs.working_directory }}

      - name: Apply Terraform
        run: terraform apply -input=false -auto-approve ${{
            inputs.plan_file_name }}
        working-directory: ${{ inputs.working_directory }}