# .github/workflows/stages.deploy.yml
name: Terraform CI/CD Orchestration

on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Terraform version'
        required: false
        default: 'latest'
        type: string
      working_directory:
        description: 'Working directory'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      backend_configs:
        description: 'Backend configuration settings'
        required: true
        type: object
      plan_file_name:
        description: 'Terraform plan file name'
        required: false
        default: 'terraform.tfplan'
        type: string
      var_file:
        description: 'Terraform variables file'
        required: false
        default: ''
        type: string

jobs:
  validate:
    name: Validate Stage
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

  #     - name: Call Install Workflow
  #       uses: ./tf_install_task.yml
  #       with:
  #         tf_version: ${{ inputs.tf_version }}

  #     - name: Call Init Workflow
  #       uses: ./tf_init_task.yml
  #       with:
  #         working_directory: ${{ inputs.working_directory }}
  #         backend_configs: ${{ inputs.backend_configs }}

  #     - name: Call Validate Workflow
  #       uses: ./tf_validate_task.yml
  #       with:
  #         working_directory: ${{ inputs.working_directory }}

  #     - name: Call Format Workflow
  #       uses: ./tf_format_task.yml
  #       with:
  #         working_directory: ${{ inputs.working_directory }}

  # plan:
  #   name: Plan Stage
  #   runs-on: ubuntu-latest
  #   needs: validate
  #   steps:
  #     - name: Call Install Workflow
  #       uses: ./tf_install_task.yml
  #       with:
  #         tf_version: ${{ inputs.tf_version }}

  #     - name: Call Init Workflow
  #       uses: ./tf_init_task.yml
  #       with:
  #         working_directory: ${{ inputs.working_directory }}
  #         backend_configs: ${{ inputs.backend_configs }}

  #     - name: Call Plan Workflow
  #       uses: ./tf_plan_task.yml
  #       with:
  #         working_directory: ${{ inputs.working_directory }}
  #         plan_file_name: ${{ inputs.plan_file_name }}
  #         var_file: ${{ inputs.var_file }}

  # apply:
  #   name: Apply Stage
  #   runs-on: ubuntu-latest
  #   needs: plan
  #   steps:
  #     - name: Call Install Workflow
  #       uses: ./tf_install_task.yml
  #       with:
  #         tf_version: ${{ inputs.tf_version }}

  #     - name: Call Init Workflow
  #       uses: ./tf_init_task.yml
  #       with:
  #         working_directory: ${{ inputs.working_directory }}
  #         backend_configs: ${{ inputs.backend_configs }}

  #     - name: Call Apply Workflow
  #       uses: ./tf_apply_task.yml
  #       with:
  #         working_directory: ${{ inputs.working_directory }}
  #         plan_file_name: ${{ inputs.plan_file_name }}
