# .github/workflows/validate.yml
name: Terraform Validate

on:
  workflow_call:
    inputs:
      gh_environment:
        required: true
        type: string

jobs:
  login:
    uses: casa-de-vops/terraform-code-standards/.github/workflows/az_login_task.yml@github_actions
    secrets: inherit
    with:
      gh_environment: ${{ inputs.gh_environment }}
  install:
    needs: login
    uses: casa-de-vops/terraform-code-standards/.github/workflows/tf_install_task.yml@github_actions
