# .github/workflows/validate.yml
name: Terraform Validate

on:
  workflow_call:
    inputs:
      tf_version:
        required: true
        type: string

jobs:
#   validate:
#     name: Terraform Validate
#     runs-on: ubuntu-latest
#     steps:
#       - name: Terraform Validate
#         run: terraform validate -chdir=${{ inputs.working_directory }}

  validate:
    name: Validate Stage
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: echo "Hello World! ${{ inputs.tf_version }}"
